-- MySQL Script generated by MySQL Workbench
-- 09/30/19 13:46:02
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema ecopilhas
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ecopilhas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ecopilhas` DEFAULT CHARACTER SET latin1 COLLATE latin1_general_ci ;
USE `ecopilhas` ;

-- -----------------------------------------------------
-- Table `ecopilhas`.`TipoUsuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecopilhas`.`TipoUsuario` (
  `idTipoUsuario` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `tipo` VARCHAR(45) CHARACTER SET 'latin1' COLLATE 'latin1_general_ci' NOT NULL COMMENT '',
  PRIMARY KEY (`idTipoUsuario`)  COMMENT '')
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = latin1
COLLATE = latin1_general_ci;


-- -----------------------------------------------------
-- Table `ecopilhas`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecopilhas`.`Usuario` (
  `idUsuario` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `nome` VARCHAR(50) CHARACTER SET 'latin1' COLLATE 'latin1_general_ci' NOT NULL COMMENT '',
  `sobrenome` VARCHAR(200) CHARACTER SET 'latin1' COLLATE 'latin1_general_ci' NOT NULL COMMENT '',
  `usuario` VARCHAR(50) CHARACTER SET 'latin1' COLLATE 'latin1_general_ci' NOT NULL COMMENT '',
  `email` VARCHAR(45) CHARACTER SET 'latin1' COLLATE 'latin1_general_ci' NOT NULL COMMENT '',
  `senha` VARCHAR(50) CHARACTER SET 'latin1' COLLATE 'latin1_general_ci' NOT NULL COMMENT '',
  `nomeSite` VARCHAR(200) CHARACTER SET 'latin1' COLLATE 'latin1_general_ci' NOT NULL DEFAULT 'EcoPilhas' COMMENT '',
  `TipoUsuario_idTipoUsuario` INT(11) NOT NULL COMMENT '',
  `ativo` TINYINT(1) NOT NULL DEFAULT '1' COMMENT '',
  PRIMARY KEY (`idUsuario`)  COMMENT '',
  UNIQUE INDEX `usuario_UNIQUE` (`usuario` ASC)  COMMENT '',
  UNIQUE INDEX `email_UNIQUE` (`email` ASC)  COMMENT '',
  INDEX `fk_Usuario_TipoUsuario_idx` (`TipoUsuario_idTipoUsuario` ASC)  COMMENT '',
  CONSTRAINT `fk_Usuario_TipoUsuario`
    FOREIGN KEY (`TipoUsuario_idTipoUsuario`)
    REFERENCES `ecopilhas`.`TipoUsuario` (`idTipoUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = latin1
COLLATE = latin1_general_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
